### ISSUE TITLE
Meta-issue on remaining Transfuse issues

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-nno-nob#2]
* [ ] Long HTML-documents getting cut off (reported?)
* [x] docx-files with document{0..n}.xml and not just document.xml are ignored https://github.com/TinoDidriksen/Transfuse/issues/14
* [x] spaces around <embed>-tags get removed https://github.com/TinoDidriksen/Transfuse/issues/16
* [x] email addresses inside `<a>` get weird https://github.com/GrammarSoft/cg3/issues/79
* [x] nested runs which give invisible text https://github.com/TinoDidriksen/Transfuse/issues/19 – actually https://github.com/apertium/lttoolbox/issues/145
* [x] https://github.com/apertium/apertium/issues/217
* [x] https://github.com/TinoDidriksen/Transfuse/issues/28

Possibly also
- [x] CDATA is lost https://github.com/TinoDidriksen/Transfuse/issues/13
- [x] Google Docs docx files crash https://github.com/TinoDidriksen/Transfuse/issues/10

**Comment by unhammer** [comment]
```
$ echo '<p>Mannens epost er <a href="mailto:foo.fie@bar.no">foo.fie@bar.no</a> og kan konta
ktes mellom ni og 09.'  | apertium -f html -u -d . nob-nno
<p>E-posten til mannen er <a href="mailto:foo.fie@bar.no">foo.fie@bar.no</a> og kan kontaktast mellom ni og 09.</p>
```
